### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by diskmanti** [DarkPurple141/Maps#1]
Hello,

First of all I wanted to say that what you achieved is amazing. Also I wanted to thank you for you great work.

I just wanted to know how to use the setup() you mentioned to modify the generated map nad how can I export the map.

Thanks again
Cheers

**Comment by DarkPurple141** [comment]
EDIT: I've since added a demo function if you pull again.

If you create a new python file 'new.py' in the existing folder then:

```
import voronoi as v

## initialises the map with default parameters
size,polygons,poly_site,river_list,city_sites,road_list,regions = v.setup()

## initialise pygame
pygame.init()
pygame.font.init()

## cardinal font 
city_font = pygame.font.SysFont('cardinal', 20) 
region_font = pygame.font.SysFont('cardinal', 30)

screen = pygame.display.set_mode(size)

pre_render(polygons,poly_site)
render_rivers(river_list)
render_roads(road_list)

## save image as test.png
pygame.image.save(screen,'test.png') 


```

You won't need the font initialisation unless you call render_cities() and render_regions().

There's a messy bit of code at the bottom of voronoi that goes through the project. If you just run voronoi.py as main it should produce an image. The setup function inside voronoi.py also has some explainer comments.

Make sure you have the necessary libraries as well.

pip3 install pygame
pip3 install numpy
pip3 install triangle

**Comment by diskmanti** [comment]
Thanks for the quick reply. 😄
